# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('restricted', models.BooleanField(default=True)),
                ('type', models.IntegerField(choices=[(0, 'Pistol'), (1, 'Rifle')])),
                ('charge', models.IntegerField(choices=[(0, 'Air'), (1, 'Gunpowder'), (2, 'Blackpowder')])),
                ('calibre', models.DecimalField(decimal_places=3, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
