# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('firearm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.IntegerField(choices=[(0, 'Bicester'), (1, 'Chesterton')])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('session', models.IntegerField(choices=[(0, 'Practice'), (1, 'Competition')])),
                ('firearm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firearm.Firearm')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
    ]
